### ISSUE TITLE
Stuck When used

### ISSUE THREAD

**Issue by flaming-archer** [innogames/polysh#23]
I like polysh very much.
But recently I found polysh is easy to stuck.
The cpu is 100%
When i ctrl + c, then display 
suTraceback (most recent call last):
  File "/xxxxx/polysh/run.py", line 22, in <module>
    run()
  File "/xxxxx/polysh/main.py", line 277, in run
    loop(args.interactive)
  File "/xxxxx/polysh/main.py", line 169, in loop
    console_output(b'')
  File "/xxxxx/polysh/console.py", line 47, in console_output
    the_stdin_thread.no_raw_input()
  File "/xxxxx/polysh/stdin.py", line 266, in no_raw_input
    interrupt_stdin_thread()
  File "/xxxxx/polysh/polysh/stdin.py", line 191, in interrupt_stdin_thread
    assert not the_stdin_thread.interrupt_asked  # Sanity check
AssertionError
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/xxxxx/polysh/main.py", line 219, in <lambda>
    atexit.register(lambda: termios.tcsetattr(fd, termios.TCSADRAIN, old))
termios.error: (25, 'Inappropriate ioctl for device')

**Comment by kofrezo** [comment]
Hi @flaming-archer,

Glad to here you like polysh. 

Do you have steps to reproduce this issue ? 

I tried connecting to a few hundreds hosts and ran a few commands and had no luck seeing it burn CPU and getting stuck.  

Information about your environment like Python version and OS could be helpful too.

**Comment by RonjaPonja** [comment]
Terminal emulator and version would also be interesting.

**Comment by flaming-archer** [comment]
Python 3.8.10
MacBook Pro (16-inch, 2019) macOS Big sur version 11.6 20G165
Iterm2 Build 3.4.9
Steps:
python3 /xxxx/run.py host1 host2 ...
then do some command like ls cat ..
then stuck.

I doubt whether ssh stable should stuck. For example, when ssh suddenly lost connection or connect need too much time.

**Comment by kofrezo** [comment]
Hey @flaming-archer,

I am able to reproduce as similar behaviour on Mac OS. It seems not to happen on my daily Linux OS. I'll try to debug it on my private Mac when I have some time.

**Comment by RonjaPonja** [comment]
FWIF I think there were always issues with polysh on macos. One issue was that apples patched ssh agent was slow and would sometimes randomly fail when connecting to too many hosts at once. CC @Woellchen who maybe remembers more as he actually used this at work.

**Comment by shuosiw** [comment]
hi, @kofrezo @HerrSpace .  I have the some problem in wsl( with ubuntu)

```
polysh --hosts-file iplist.txt
waiting (10/10)> Traceback (most recent call last):
  File "/usr/local/bin/polysh", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/polysh/main.py", line 300, in main
    run()
  File "/usr/local/lib/python3.6/dist-packages/polysh/main.py", line 276, in run
    loop(args.interactive)
  File "/usr/local/lib/python3.6/dist-packages/polysh/main.py", line 178, in loop
    console_output(b'')
  File "/usr/local/lib/python3.6/dist-packages/polysh/console.py", line 47, in console_output
    the_stdin_thread.no_raw_input()
  File "/usr/local/lib/python3.6/dist-packages/polysh/stdin.py", line 266, in no_raw_input
    interrupt_stdin_thread()
  File "/usr/local/lib/python3.6/dist-packages/polysh/stdin.py", line 196, in interrupt_stdin_thread
    os.kill(pid, signal.SIGWINCH)  # Try harder to wake up raw_input()
ProcessLookupError: [Errno 3] No such process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/polysh/main.py", line 218, in <lambda>
    atexit.register(lambda: termios.tcsetattr(fd, termios.TCSADRAIN, old))
termios.error: (25, 'Inappropriate ioctl for device')
```

my environments is:

* OS: windows 11
* wsl: Ubuntu 18.04.2 LTS
* python: 3.6.7

**Comment by kofrezo** [comment]
Hi @shuosiw,

I will try to have another look at it when I have some spare time.

**Comment by kofrezo** [comment]
We have some people working succefully with WSL without problem today so I assume this is working again. Feel free to open this again if there is still a problem.
